{% set name = "ellc" %}
{% set version = "1.8.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ellc-{{ version }}.tar.gz
  sha256: f89553541d1931a1ef63dd27f1c32f193482e88a70a90831808c2f21c2032d63

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - numpy
    - pip
    - python
  run:
    - astropy-base >=1.1.1
    - numpy >=1.10.0
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ellc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pmaxted/ellc
  summary: Light curve model for eclipsing binary stars and transiting exoplanets
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mwcraig
